name: Pull request
on: pull_request

jobs:
  pull-request:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.3"

    - name: Setup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl https://mise.run | sh
        mise install

    - name: Lint
      run: mise lint

    - name: Build
      run: swift build

    - name: Test
      run: swift test