name: Pull request
on: pull_request

env:
  XCODE_VERSION: "16.3"

jobs:
  pull-request:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app

    - name: Setup mise
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl https://mise.run | sh
        mise install

    - name: Lint
      run: mise lint

    - name: Build
      run: swift build

    - name: Test
      run: swift test