name: Pull request
on: pull_request

jobs:
  prepare:
    runs-on: macos-15
    outputs:
      platforms: ${{ steps.extract.outputs.platforms }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Swift
      uses: slashmo/install-swift@main
      with:
        version: 6.1
    - name: Setup mise
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl https://mise.run | sh
        mise install
    - name: Lint
      run: mise lint
    - name: Extract platforms
      id: extract
      run: |
        platforms=$(swift package dump-package | jq -r '[.platforms[].platformName] | unique | @json')
        echo "Platforms: $platforms"
        echo "platforms=$platforms" >> $GITHUB_OUTPUT